language: python
python:
  - "2.7"
install:
  - "easy_install -U setuptools"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: "coverage run --source=swift_collate setup.py test"
after_success:
  coveralls
